---
version: 2
jobs:
  build:
    docker:
      - image: library/docker:17
    working_directory: /tmp/build
    environment:
      DOCKER_USERNAME: travisciresin
      DOCKER_IMAGE: resin/dogpush
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker info
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - run:
          name: Build
          command: |
            docker pull ${DOCKER_IMAGE}:master || true
            docker build -t ${DOCKER_IMAGE}:${CIRCLE_SHA1} .
      - deploy:
          name: Deploy
          command: |
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
            set -x

            docker push ${DOCKER_IMAGE}:${CIRCLE_SHA1}
            docker tag ${DOCKER_IMAGE}:${CIRCLE_SHA1} ${DOCKER_IMAGE}:${CIRCLE_BRANCH}
            docker push ${DOCKER_IMAGE}:${CIRCLE_BRANCH}

            apk add --no-cache git
            tag=$(git describe --tags) || true
            if [ "${tag}" != "" ]; then
              docker tag ${DOCKER_IMAGE}:${CIRCLE_SHA1} ${DOCKER_IMAGE}:${tag}
              docker push ${DOCKER_IMAGE}:${tag}
            fi

